# 產生連接矩陣H

In [1]:
import numpy as np

from math_hypergraph import get_np_H

hyperedges = [(0, 1, 2, 4), (1, 2), (2, 3), (2, 4)]
num_nodes = 5
H = get_np_H(hyperedges, num_nodes)
print(H)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]]


In [2]:
import numpy as np
import scipy.sparse as sp

from math_hypergraph import get_sp_H

hyperedges = [(0, 1, 2), (1, 2), (2, 3), (2, 4)]
num_nodes = 5

H = get_sp_H(hyperedges, num_nodes)
print(H.toarray())

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 從 H 得到 超邊 list

In [3]:
import numpy as np
import scipy.sparse as sp

from math_hypergraph import get_hyperedges

hyperedges = get_hyperedges(H)
print(hyperedges)

[[0, 1, 2], [1, 2], [2, 3], [2, 4]]


# 從 H 計算出 鄰接矩陣adj

In [4]:
import numpy as np
import scipy.sparse as sp

from math_hypergraph import get_sp_adj_from_H

hyperedges = [(0, 1), (1, 2), (2, 3), (2, 4)]
num_nodes = 5

H = get_sp_H(hyperedges, num_nodes)
print(get_sp_adj_from_H(H).toarray())

[[0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


# 從 H 計算出 Dv^(-0.5)@H @ W@De^(-1) @ H@Dv^(-0.5)

In [5]:
import numpy as np
import scipy.sparse as sp

from math_hypergraph import get_sp_H
from math_hypergraph import get_sp_DvH_WDe_HDv

hyperedges = [(0, 1), (1, 2), (2, 3), (2, 4)]
num_nodes = 5

H = get_sp_H(hyperedges, num_nodes)
DvH_WDe_HDv = get_sp_DvH_WDe_HDv(H, W=np.ones(len(hyperedges)))
print(DvH_WDe_HDv.toarray())

[[0.5        0.35355338 0.         0.         0.        ]
 [0.35355338 0.5        0.20412415 0.         0.        ]
 [0.         0.20412415 0.5        0.28867513 0.28867513]
 [0.         0.         0.28867513 0.5        0.        ]
 [0.         0.         0.28867513 0.         0.5       ]]


# 從 H 計算出 正規化拉普拉斯 L_norm

In [6]:
import numpy as np
import scipy.sparse as sp

from math_hypergraph import get_sp_H
from math_hypergraph import get_sp_L_norm_from_H

hyperedges = [(0, 1), (1, 2), (2, 3), (2, 4)]
num_nodes = 5

H = get_sp_H(hyperedges, num_nodes)
L_norm = get_sp_L_norm_from_H(H, W=np.ones(len(hyperedges)))
print(L_norm.toarray())

[[ 0.5        -0.35355338  0.          0.          0.        ]
 [-0.35355338  0.5        -0.20412415  0.          0.        ]
 [ 0.         -0.20412415  0.5        -0.28867513 -0.28867513]
 [ 0.          0.         -0.28867513  0.5         0.        ]
 [ 0.          0.         -0.28867513  0.          0.5       ]]


# 將 L_norm 做chebyshev輸入的正規化

In [7]:
import numpy as np
import scipy.sparse as sp

from math_hypergraph import get_sp_H
from math_hypergraph import get_sp_L_chebyshev_norm_from_H

hyperedges = [(0, 1), (1, 2), (2, 3), (2, 4)]
num_nodes = 5

H = get_sp_H(hyperedges, num_nodes)
L_norm = get_sp_L_chebyshev_norm_from_H(H,
                                        W=np.ones(len(hyperedges)),
                                        lambda_max=2.0)
print(L_norm.toarray())

[[-0.5        -0.35355338  0.          0.          0.        ]
 [-0.35355338 -0.5        -0.20412415  0.          0.        ]
 [ 0.         -0.20412415 -0.5        -0.28867513 -0.28867513]
 [ 0.          0.         -0.28867513 -0.5         0.        ]
 [ 0.          0.         -0.28867513  0.         -0.5       ]]
