In [1]:
import tensorflow as tf
import numpy as np
import scipy.sparse as sp

def get_adj(edges: list, num_nodes: int):
    e_rows, e_cols = np.array(edges, dtype=np.int).transpose()
    values = np.ones(shape=(len(e_rows), ), dtype=np.float32)
    adj = sp.coo_matrix((values, (e_rows, e_cols)),
                        shape=[num_nodes, num_nodes])
    # triu adj --> adj
    adj.setdiag(0)
    bigger = adj.T > adj
    adj = adj - adj.multiply(bigger) + adj.T.multiply(bigger)
    return adj

In [2]:
W = get_adj([(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (6, 7), (7, 8), (8, 9)], 10).toarray()

W[W == 0] = -1
W = W + np.identity(W.shape[0])
W[W == -1] = float('inf')

# W[np.isinf(W)] = -1
# W[W == -1] = float('inf')

print(W)
W = np.min(np.expand_dims(W, 0)+np.expand_dims(W, 2), 1)
print(W)
W = np.min(np.expand_dims(W, 0)+np.expand_dims(W, 2), 1)
print(W)
W = np.min(np.expand_dims(W, 0)+np.expand_dims(W, 2), 1)
print(W)

[[ 0.  1. inf inf inf inf inf inf inf inf]
 [ 1.  0.  1. inf inf inf inf inf inf inf]
 [inf  1.  0.  1. inf inf inf inf inf inf]
 [inf inf  1.  0.  1. inf inf inf inf inf]
 [inf inf inf  1.  0.  1. inf inf inf inf]
 [inf inf inf inf  1.  0. inf inf inf inf]
 [inf inf inf inf inf inf  0.  1. inf inf]
 [inf inf inf inf inf inf  1.  0.  1. inf]
 [inf inf inf inf inf inf inf  1.  0.  1.]
 [inf inf inf inf inf inf inf inf  1.  0.]]
[[ 0.  1.  2. inf inf inf inf inf inf inf]
 [ 1.  0.  1.  2. inf inf inf inf inf inf]
 [ 2.  1.  0.  1.  2. inf inf inf inf inf]
 [inf  2.  1.  0.  1.  2. inf inf inf inf]
 [inf inf  2.  1.  0.  1. inf inf inf inf]
 [inf inf inf  2.  1.  0. inf inf inf inf]
 [inf inf inf inf inf inf  0.  1.  2. inf]
 [inf inf inf inf inf inf  1.  0.  1.  2.]
 [inf inf inf inf inf inf  2.  1.  0.  1.]
 [inf inf inf inf inf inf inf  2.  1.  0.]]
[[ 0.  1.  2.  3.  4. inf inf inf inf inf]
 [ 1.  0.  1.  2.  3.  4. inf inf inf inf]
 [ 2.  1.  0.  1.  2.  3. inf inf inf inf]
 [ 3.  2.

In [3]:
for iw in W:
    iw = iw.reshape([-1,1])+W
    # print(iw)
    iw = np.min(iw, axis=0)
    print(iw)

print()
np.min(np.expand_dims(W, 0)+np.expand_dims(W, 2), 1)

[ 0.  1.  2.  3.  4.  5. inf inf inf inf]
[ 1.  0.  1.  2.  3.  4. inf inf inf inf]
[ 2.  1.  0.  1.  2.  3. inf inf inf inf]
[ 3.  2.  1.  0.  1.  2. inf inf inf inf]
[ 4.  3.  2.  1.  0.  1. inf inf inf inf]
[ 5.  4.  3.  2.  1.  0. inf inf inf inf]
[inf inf inf inf inf inf  0.  1.  2.  3.]
[inf inf inf inf inf inf  1.  0.  1.  2.]
[inf inf inf inf inf inf  2.  1.  0.  1.]
[inf inf inf inf inf inf  3.  2.  1.  0.]



array([[ 0.,  1.,  2.,  3.,  4.,  5., inf, inf, inf, inf],
       [ 1.,  0.,  1.,  2.,  3.,  4., inf, inf, inf, inf],
       [ 2.,  1.,  0.,  1.,  2.,  3., inf, inf, inf, inf],
       [ 3.,  2.,  1.,  0.,  1.,  2., inf, inf, inf, inf],
       [ 4.,  3.,  2.,  1.,  0.,  1., inf, inf, inf, inf],
       [ 5.,  4.,  3.,  2.,  1.,  0., inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf,  0.,  1.,  2.,  3.],
       [inf, inf, inf, inf, inf, inf,  1.,  0.,  1.,  2.],
       [inf, inf, inf, inf, inf, inf,  2.,  1.,  0.,  1.],
       [inf, inf, inf, inf, inf, inf,  3.,  2.,  1.,  0.]])

In [4]:
for iw in W:
    iw = iw+W
    #print(iw)
    iw = np.min(iw, axis=1)
    print(iw)

print()
np.min(np.expand_dims(W, 0)+np.expand_dims(W, 1), 2)

[ 0.  1.  2.  3.  4.  5. inf inf inf inf]
[ 1.  0.  1.  2.  3.  4. inf inf inf inf]
[ 2.  1.  0.  1.  2.  3. inf inf inf inf]
[ 3.  2.  1.  0.  1.  2. inf inf inf inf]
[ 4.  3.  2.  1.  0.  1. inf inf inf inf]
[ 5.  4.  3.  2.  1.  0. inf inf inf inf]
[inf inf inf inf inf inf  0.  1.  2.  3.]
[inf inf inf inf inf inf  1.  0.  1.  2.]
[inf inf inf inf inf inf  2.  1.  0.  1.]
[inf inf inf inf inf inf  3.  2.  1.  0.]



array([[ 0.,  1.,  2.,  3.,  4.,  5., inf, inf, inf, inf],
       [ 1.,  0.,  1.,  2.,  3.,  4., inf, inf, inf, inf],
       [ 2.,  1.,  0.,  1.,  2.,  3., inf, inf, inf, inf],
       [ 3.,  2.,  1.,  0.,  1.,  2., inf, inf, inf, inf],
       [ 4.,  3.,  2.,  1.,  0.,  1., inf, inf, inf, inf],
       [ 5.,  4.,  3.,  2.,  1.,  0., inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf,  0.,  1.,  2.,  3.],
       [inf, inf, inf, inf, inf, inf,  1.,  0.,  1.,  2.],
       [inf, inf, inf, inf, inf, inf,  2.,  1.,  0.,  1.],
       [inf, inf, inf, inf, inf, inf,  3.,  2.,  1.,  0.]])

# tensorflow

In [5]:
W = get_adj([(0, 1), (1, 2), (2, 3), (3, 4), (4, 5),  (6, 7), (7, 8), (8, 9)], 10).toarray()

W[W == 0] = -1
W = W + np.identity(W.shape[0])
W[W == -1] = float('inf')
W = W.astype('float32')

W = tf.convert_to_tensor(W)

print(W)
#W = tf.reduce_min(tf.expand_dims(W, 0)+tf.expand_dims(W, 2), 1)
W = tf.stack([tf.reduce_min(iw+W, 0) for iw in tf.expand_dims(W, 2)])
print(W)
#W = tf.reduce_min(tf.expand_dims(W, 0)+tf.expand_dims(W, 2), 1)
W = tf.stack([tf.reduce_min(iw+W, 0) for iw in tf.expand_dims(W, 2)])
print(W)
#W = tf.reduce_min(tf.expand_dims(W, 0)+tf.expand_dims(W, 2), 1)
W = tf.stack([tf.reduce_min(iw+W, 0) for iw in tf.expand_dims(W, 2)])
print(W)

tf.Tensor(
[[ 0.  1. inf inf inf inf inf inf inf inf]
 [ 1.  0.  1. inf inf inf inf inf inf inf]
 [inf  1.  0.  1. inf inf inf inf inf inf]
 [inf inf  1.  0.  1. inf inf inf inf inf]
 [inf inf inf  1.  0.  1. inf inf inf inf]
 [inf inf inf inf  1.  0. inf inf inf inf]
 [inf inf inf inf inf inf  0.  1. inf inf]
 [inf inf inf inf inf inf  1.  0.  1. inf]
 [inf inf inf inf inf inf inf  1.  0.  1.]
 [inf inf inf inf inf inf inf inf  1.  0.]], shape=(10, 10), dtype=float32)
tf.Tensor(
[[ 0.  1.  2. inf inf inf inf inf inf inf]
 [ 1.  0.  1.  2. inf inf inf inf inf inf]
 [ 2.  1.  0.  1.  2. inf inf inf inf inf]
 [inf  2.  1.  0.  1.  2. inf inf inf inf]
 [inf inf  2.  1.  0.  1. inf inf inf inf]
 [inf inf inf  2.  1.  0. inf inf inf inf]
 [inf inf inf inf inf inf  0.  1.  2. inf]
 [inf inf inf inf inf inf  1.  0.  1.  2.]
 [inf inf inf inf inf inf  2.  1.  0.  1.]
 [inf inf inf inf inf inf inf  2.  1.  0.]], shape=(10, 10), dtype=float32)
tf.Tensor(
[[ 0.  1.  2.  3.  4. inf inf inf inf inf

In [6]:
def dist_W(dW, K=None):
    # 疊代 K次，計算節點與節點之間最點距離
    # dW 為 graph的距離矩陣
    # dw的值 為 [0~inf)
    # dw.shape = [num_N, num_N]
    num_N = dW.shape[0]
    max_K = int(np.ceil(np.log2(num_N)))
    #print(f'max_K={max_K}, K={K}')
    if K is not None and K < max_K:
        max_K = K
    for i in range(max_K):
        dW_odd = dW
        dW = tf.expand_dims(dW, 0)+tf.expand_dims(dW, 2) # [N,N,N]
        dW = tf.reduce_min(dW, 1)
        if tf.math.reduce_all(tf.equal(dW, dW_odd)):
            #print('break')
            break
        #print(f'{i} {dW}')
    return dW

def dist_H_from_adj(adj, N=None, K=None):
    W = np.array(adj, 'float32')
    W[W == 0] = float('inf')
    np.fill_diagonal(W, 0)
    W = tf.convert_to_tensor(W)
    # dW 計算節點與節點 的距離
    dW = dist_W(W, K=K)
    print(dW)
    if N is None:
        dW = tf.cast(tf.logical_not(tf.math.is_inf(dW)), 'float32')
    else:
        dW = tf.cast(tf.less_equal(dW, N), 'float32')
    H = sp.coo_matrix(dW.numpy())
    return H

adj = get_adj([(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5,6), (6, 7), (7, 8), (8, 9)], 10).toarray()
dist_H_from_adj(adj, 3, 1).toarray()

tf.Tensor(
[[ 0.  1.  2. inf inf inf inf inf inf inf]
 [ 1.  0.  1.  2. inf inf inf inf inf inf]
 [ 2.  1.  0.  1.  2. inf inf inf inf inf]
 [inf  2.  1.  0.  1.  2. inf inf inf inf]
 [inf inf  2.  1.  0.  1.  2. inf inf inf]
 [inf inf inf  2.  1.  0.  1.  2. inf inf]
 [inf inf inf inf  2.  1.  0.  1.  2. inf]
 [inf inf inf inf inf  2.  1.  0.  1.  2.]
 [inf inf inf inf inf inf  2.  1.  0.  1.]
 [inf inf inf inf inf inf inf  2.  1.  0.]], shape=(10, 10), dtype=float32)


array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]], dtype=float32)